### ISSUE TITLE
Descriptor formatting

### ISSUE THREAD

**Issue by jsomara** [herosheets/woin-characters#23]
- the descriptor is not correctly formed. It should include age, trait, race, career, hook.

**Comment by seiyria** [comment]
not sure how this should look with multiple careers, but the rest is done.

**Comment by jsomara** [comment]
@seiyria @Morrus using http://www.woinrpg.com/murphy/ as a guide, careers dont show up in the descriptor

**Comment by seiyria** [comment]
in that case, it's done.

**Comment by Morrus** [comment]
Yes they do.

A reckless human smuggler who loves playing cards

An illiterate Ogron star marine who loves to watch sports

An erudite Android medic who is fascinated by religion

A young disfigured Venetian star knight who believes in fairytales

An ambidextrous Felan burglar who plays classical music

An alcoholic human psychic who collects insects

Do you not have the PDF of the book I sent you?  It explains how the the descriptor is formed.

If not, there is also an explanation here:

http://www.woinrpg.com/descriptor/

a[n] [age] [trait] [race] [caree] who [hook].

**Comment by seiyria** [comment]
Okay, so in that case, my original question was "what happens when there are multiple careers" and that still needs answering.

**Comment by Morrus** [comment]
It's in the book I sent you. You use the current career or the longest served one. If the latter isn't current, you prefix it with "-ex".

Sent from my iPhone

On 30 Jul 2016, at 14:43, Kyle J. Kemp <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay, so in that case, my original question was "what happens when there are multiple careers" and that still needs answering.

##
